FROM pedrombmachado/ntu_lubuntu:comp20081
RUN apt-get update && apt-get install -y openjdk-11-jdk && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY JavaFXApplication1/target/JavaFXApplication1-1.0-SNAPSHOT.jar app.jar
CMD ["java", "-cp", "app.jar", "com.mycompany.javafxapplication1.StorageServer"]